server:
    ##端口号
    port: 9988
spring:
  application:
    name: spring-boot-mail
#######个人邮箱配置规则#######　
#  mail:
#      ##编码格式
#      default-encoding: UTF-8
#      ##这里根据自己的情况填写
#      ##邮箱服务器地址
#      ##QQ smtp.qq.com
#      ##sina smtp.sina.cn
#      ##aliyun smtp.aliyun.com
#      ##163 smtp.163.com
#      host: smtp.qq.com
#      ##邮箱密码（注意：qq邮箱应该使用独立密码，去qq邮箱设置里面获取）
#      password: xxxxxxxxx
#      ##邮箱用户名
#      username: xxxxxxxxx@xxx.com
#      properties:
#        mail:
#          smtp:
#            auth: true
#            socketFactory:
#              fallback: false
#              port: 587
#######个人邮箱配置规则#######　
########企业邮箱配置规则#######
  mail:
    ##编码格式
    default-encoding: UTF-8
    ##这里根据自己的情况填写
    ##邮箱服务器地址
    ##QQ smtp.qq.com
    ##sina smtp.sina.cn
    ##aliyun smtp.aliyun.com
    ##163 smtp.163.com
    host: smtp.mxhichina.com
    ##邮箱密码（注意：qq邮箱应该使用独立密码，去qq邮箱设置里面获取）
    password: xxxxxxxxx
    ##邮箱用户名
    username: xxxxxxxxx@xxx.com
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          socketFactory:
            fallback: false
            port: 587
########企业邮箱配置规则########